apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssh-term
  namespace: ssh-term
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
spec:
  ingressClassName: nginx
  rules:
    - host: ssh.whexy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssh-term
                port:
                  number: 8080
